name: lab8_workflow

on:
  push:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        pytest main/calculator_test.py

  functional_test:
    needs: unit_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run app
      run: |
        python main/app.py &
        sleep 5
    - name: Functional tests
      run: |
        pytest main/app_test.py

  deployment:
    needs: functional_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME_416312 }}
        password: ${{ secrets.DOCKERHUB_TOKEN_416312 }}
    - name: Debug list all
      run: |
        ls -l
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME_416312 }}/dev_ops_laby:latest
